### ISSUE TITLE
Service Feasibility - Default values or validation value is set for user defined values

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#126]
Needed to change the default Attribute Parameter to User Defined then give a ratio.  Now the widget works.  For go live, we should default it to this setting with some default range.
![influence](https://cloud.githubusercontent.com/assets/11183838/7126814/672c7826-e1f1-11e4-8c64-393d255c37ee.png)

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam Please advise if this is a issue we can fix or just have to accept the user needs to provide the correct configuration.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, 
Not sure if we can fix this.
When user input is allowed, there is no way for us to know the allowable range of values, so we cannot prepopulate that by default. We don't even know if a range specified by user is acceptable by the service or not, since ArcGIS REST API does not provide this information.

We are open to any suggestions from your side.

**Comment by MikeMillerGIS** [comment]
Closing issue as there is no fix @CTLocalGovTeam
