### ISSUE TITLE
Service Feasibility - Setting default units from what is defined in the service

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#127]
The NA service already has units by default selected.  Carry this over to the specify units in the widget.
![units](https://cloud.githubusercontent.com/assets/11183838/7125944/34f25e0e-e1ea-11e4-85cd-2402687cbffa.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS,
The widget does not request for driving directions, and the 'Directions Length Units' is honored only by the driving directions. The widget actually uses the `returnCFRoutes=true` to generate the route and `returnDirections=false`. 

We analyzed and found that the units of the route is entirely dependent on the `outSpatialReference` specified in the request to find closest facility. The widget sets this to the map's spatial reference. So actually, whatever is currently displayed in the UI is actually in meters (since the basemaps are in 102100). 

For the text box where users have to configure the label of the unit, we feel that we can either
* auto-populate the unit from basemap's spatial reference or
* remove the configuration parameter and display units directly from basemap's spatial reference, however we lose ability to localize the unit label text.

Please suggest.

**Comment by MikeMillerGIS** [comment]
I do not think either makes sense.  Lets leave it as is, closing the issue @CTLocalGovTeam
