### ISSUE TITLE
Service Feasibility - Error solving route issues

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#130]
Business Influence value is very inconsistent.  Some areas, a zero value results in an error, other places, the zero value returns results.
![lengthtoratio](https://cloud.githubusercontent.com/assets/11183838/7127371/087723ec-e1f8-11e4-90a1-89547aa1c1e0.png)
Error message for unsuccessful routing should be more descriptive so users know what happen.  Such as was the network service down, the influence parameter is not right, etc.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are not able reproduce this with [this] (http://54.203.249.87:6080/arcgis/rest/services/A4TC/ServiceQualificationRoute/NAServer/Closest%20Facility) closest facility service used in the tryitlive link, but we are able to see this issue with [AGOL routing service](http://route.arcgis.com/arcgis/rest/services/World/ClosestFacility/NAServer/ClosestFacility_World). 

Do you also see the same behavior ?

**Comment by MikeMillerGIS** [comment]
@clareprice Can you confirm this?

**Comment by clareprice** [comment]
@MikeMillerGIS I was not able to reproduce an error with the sample closet facility service and sample data.

**Comment by MikeMillerGIS** [comment]
@clareprice do you get the error only with the AGO routing service then?

**Comment by clareprice** [comment]
@MikeMillerGIS When through and tested this issue again. It is very inconsistence in error messages. During this testing, I was able to reproduce an error with the try it live closest facility and not with an AGOL closest facility. Just very inconsistent and error message is very generic that it is difficult to understand why there is an error.

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam Is there a way to improve the error messaging to help the user determine what is going wrong?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS , @clareprice,
We were able to reproduce this error consistently with AGOL routing service only with one specific scenario. AGOL ClosestFacility service supports only 100 facilities. So, only in cases where more than 100 facilities are found in the buffer, the solve fails and displays this error message. 

We have not been able to reproduce this using the tryitlive closest facility. This is most probably because the limit of facilities for an ArcGIS NAServer ClosestFacility service is much larger, like 1000. 

Would you like us to display the error message that is returned by the server? Sometimes, this may get too technical for an average user to understand.

**Comment by MikeMillerGIS** [comment]
There are limits using the synchronously version of the service.  
http://resources.arcgis.com/en/help/arcgis-rest-api/#/Closest_Facility_service_with_synchronous_execution/02r3000000n7000000/

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, @clareprice, 
That is correct, and the widget supports using only synchronous version of AGOL ClosestFacility service. 

Please let us know if you'd you like us to display the error message that is returned by the server?

**Comment by MikeMillerGIS** [comment]
How does this sound:  You have exceeded the limit of the configured routing service.  Please include this in the NLS. @CTLocalGovTeam @clareprice

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, @clareprice,
Implementing a custom error message may not be possible since there could be other reasons too for a failure.
Will need to check if AGOL and ArcGIS server return the same error code/message/details when limit is exceeded. Are you suggesting we handle this by trapping the error message from service and then display this custom message?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, @clareprice, 

We checked with tryitlive closest facility service and were able to successfully solve for more than 1000 facilities. We went up to 3000 facilities and were still able to successfully solve the route. 
When using the widget with tryitlive service, we are still unable to reproduce the "error solving route" message.

Please let us know how you would like us to proceed on this.

Do you want us to implement a custom error message just for AGOL service limit exceeded?

**Comment by MikeMillerGIS** [comment]
If possible, yes

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, @clareprice,
The error message returned by AGOL when limit is exceeded is this.
```javascript
{
    "error": {
        "code": 400,
        "message": "Unable to complete operation.",
        "details": [
            "The number of input locations loaded into Facilities exceeded the maximum of 100 allowed by the service."
        ]
    }
}
```
If we have to implement a custom error message for this, then we'd have to look at `details` and do an exact string match (case insensitive). Then pick the custom error message from NLS and display.
Is this ok?

**Comment by MikeMillerGIS** [comment]
Just display the details from the error

**Comment by MikeMillerGIS** [comment]
Just display the details from the error

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, thanks for the quick confirmation. Do you want us to display the details for any error message returned by the server or only for limit exceeded by doing a string match?

**Comment by MikeMillerGIS** [comment]
All error messages

Sent from my Verizon Wireless 4G LTE DROID
On May 8, 2015 6:01 AM, CyberTech <notifications@github.com> wrote:

@MikeMillerGIS<https://github.com/MikeMillerGIS>, thanks for the quick confirmation. Do you want us to display the details for any error message returned by the server or only for limit exceeded by doing a string match?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will display a message when any error occurs while solving the route. We suggest the contents of the message to be \<message\> - \<details\>. This is because, often error messages from server includes a message but does not include details.

For e.g. `Unable to complete operation. - The number of input locations loaded into Facilities exceeded the maximum of 100 allowed by the service.`

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We have implemented this and will be incorporating in 6/10 release.

**Comment by MikeMillerGIS** [comment]
verified
