### ISSUE TITLE
Network Trace - Option to not save an output parameter into an Overview field

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#139]
Currently, you have to define a field for each output parameter.  Saving an output to an field in the overview should be optional.

Example.  My Model returns Valves, Hydrants, Customers.  In my overview, I only want to save the valves to a field in the overview layer.

@clareprice

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Currently, the field mapping is not optional. Users have to map fields for all the output parameters. We are thinking that to make them optional, we can provide a 'None' option in the field name dropdown. All field names will default to 'None' on load. 

We also feel that showing parameter names in a drop down does not make sense, since we do not allow selection of same output parameter more than once. Instead, we think we should display all the parameter names as static labels with field name option for each of them as shown in this graphic below.

Please let us know what you think of this.

![capture](https://cloud.githubusercontent.com/assets/2959186/7453677/59e47134-f289-11e4-9f3e-c5e4ef358356.PNG)

**Comment by MikeMillerGIS** [comment]
Yes, I like that layout and the option for None. @CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are ok to implement this change. Can we please change the label to an appropriate one like change/enhancement?

**Comment by MikeMillerGIS** [comment]
verefied
