### ISSUE TITLE
Service Qualification - IE 8 User Experience

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#146]
When using a configuration of service qualification in IE8, after the app finally loads and the user is able to place a point of the map, the following error message will occur when running 
![ie8](https://cloud.githubusercontent.com/assets/5611508/7479739/70f46af2-f318-11e4-951e-f67eabf9322b.jpg)

Select yes and the widget continued and results were displayed in the widget but nothing on the map.
![image](https://cloud.githubusercontent.com/assets/5611508/7479763/8f5c462c-f318-11e4-8121-d801cc61d0f6.png)

Finally when trying to actually navigate in the map or select a business from the results, browser and app just stop.
![image](https://cloud.githubusercontent.com/assets/5611508/7479780/accca8a0-f318-11e4-9c8d-2eba1fba2eb9.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice, @MikeMillerGIS, We are able to repro this only when we configure a large buffer value (e.g., 20,000 feet) that returns lot of businesses (> 1000). This is because IE8 browser's rendering engine struggles to display large number of graphics on the map.

We see the 'long running script' message for smaller buffer values too. You have to click through them and wait, and it eventually displays the results. However, the app does not freeze. The browser/app gets very sluggish though.

Are you seeing the app freeze consistently for smaller buffer values?

**Comment by clareprice** [comment]
@CTLocalGovTeam Yes, for smaller buffers (approx 250 businesses passed and less than 2000 feet) the app would still freeze.

**Comment by MikeMillerGIS** [comment]
@clareprice can you see if this is still happening and if so, mark as known issue

**Comment by MikeMillerGIS** [comment]
closing
