### ISSUE TITLE
Service Feasibility - No way to define inputs for numeric types

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#152]
When a parameter is a type, like height, weight, there is no way to input a value.

![image](https://cloud.githubusercontent.com/assets/2707285/7523568/860c32c2-f4ca-11e4-9b46-d239ed653005.png)

![image](https://cloud.githubusercontent.com/assets/2707285/7523589/a625a886-f4ca-11e4-8fe8-71d4ff9a3c1e.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS `Height Limit and` and `Height Restriction` are two different network attributes, but only `Height Restriction` is an attribute parameter value. Since `Height Restriction` is not an integer/double data type,  

![image](https://cloud.githubusercontent.com/assets/2959186/7609731/e51a8cd2-f993-11e4-94bb-67c70eba64e9.png)

we are displaying the attribute parameter lookup values(`Prohibited, Avoid High, Avoid Medium, etc.`) in a dropdown for this. We see that this issue is related to issue #151.

**Comment by MikeMillerGIS** [comment]
There is still no way to enter a value for these parameters.  If I set it to allow user input, I get the drop down for the integer.double parameter, not the min/max value.  I think this is due to two parameters have the same name, but different types.  @CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS,

When we are looking at attribute parameter values, we see the parameter value named `Vehicle Height (meters)` under an attributeName `Height Restriction`. However, the datatype of `Height Restriction` attribute is boolean. How do we determine the datatype of `Vehicle Height (meters)`?

![image](https://cloud.githubusercontent.com/assets/2959186/7633662/3b9e3a2e-fa73-11e4-938a-b26bbe32ddcf.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, 
We are discussing an approach for allowing users to define inputs for numeric types in  https://github.com/Esri/solutions-webappbuilder-widgets/issues/149#issuecomment-103021162.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We have implemented the approach finalized for #149. We will provide this in 6/10 release.

**Comment by MikeMillerGIS** [comment]
Verified
