### ISSUE TITLE
Network Trace - Overview edit dialog not attribute inspector

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#153]
Email sent with details

![image](https://cloud.githubusercontent.com/assets/2707285/7543738/e6059b62-f594-11e4-80a2-f960b3a9eb92.png)

**Comment by MikeMillerGIS** [comment]
![image](https://cloud.githubusercontent.com/assets/2707285/7543734/db4732ee-f594-11e4-8aad-5bd5c7da9d97.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS,
We were able to able reproduce this issue using the config.json provided to us in email.
We investigated and found that this is due to incorrect handling of Visible option of Overview configuration parameter as well as incorrect handling of polygon and polyline geometries while creating convex hull.

We were able to resolve this on our side and will include this fix in next release.

**Comment by MikeMillerGIS** [comment]
Not sure if this related, but the overview area is not including polygons if that are part of the result, the yellow is the return from the service, the smaller redish is the overview being created
![image](https://cloud.githubusercontent.com/assets/2707285/7624130/b5a1387a-f9b1-11e4-982f-ff6c56e6999a.png)

**Comment by MikeMillerGIS** [comment]
verified
