### ISSUE TITLE
Network Trace - Undefined for Skipcount

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#174]
![image](https://cloud.githubusercontent.com/assets/2707285/8065831/0c10493e-0eb2-11e5-83d8-bf0c7f9afff2.png)
![image](https://cloud.githubusercontent.com/assets/2707285/8065835/124d4702-0eb2-11e5-8cb6-cf69d1d2860b.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We are able to reproduce this issue.
The root cause of this issue is an error in NLS strings for Summary text hint, where SkipCount is erroneously configured as Skipcount (notice small c in count).

We feel that {Count} and {SkipCount} is not required to be sourced from NLS as they are constant variable names used in the widget. They can be sourced from configuration widget and the additional hint text (*This will be displayed in the summary panel for this...*) can still be sourced from NLS.

Is this acceptable?

**Comment by MikeMillerGIS** [comment]
agree

**Comment by MikeMillerGIS** [comment]
verified
