### ISSUE TITLE
Network Trace - Overview layer appears in TOC.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#220]
If possible, hide the overview layer from the TOC.

![image](https://cloud.githubusercontent.com/assets/2707285/8535960/dc39c9fc-2418-11e5-8e0d-3c43243c0431.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
The OverviewGraphicLayer is displayed in TOC because its a feature layer that's added to map. The layerlist widget automatically picks up all operational layers added to map and displays it in the list.

We are using the OverviewGraphicLayer as a featurelayer based on a featurecollection. This helps in displaying the attribute inspector while saving to Overview layer. Since all featurelayers are considered as operational layers, it is displayed in layer list widget.

We don't see an elegant way to remove it from the list. We are open to any suggestions on this one.

**Comment by MikeMillerGIS** [comment]
Makes sense, could we just change the name to Widgets name then Overview.  So if the user calls the Widget Utility Trace, the layer would be Utility Trace Overview?

**Comment by MikeMillerGIS** [comment]
Verified
