### ISSUE TITLE
Service Feasibility - Leverage Travel Modes

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#224]
In the latest release of ArcGIS Online, travel modes have been added.  Can we support these, do they make sense?

**Comment by HWest-Esri** [comment]
Travel modes like "walking", "driving", "driving a truck", etc? If so then yea I think they definitely make sense for avoiding certain undesirable traffic things, but I think that the underlying network dataset should be configured so that the app respects that.

**Comment by MikeMillerGIS** [comment]
![image](https://cloud.githubusercontent.com/assets/2707285/8753514/680822f2-2c8a-11e5-85db-4b9ebb91115c.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We are assuming that you want the driving mode option to be selectable from a dropdown in the widget UI. This can be placed at step no. 2 in the widget UI. Please confirm.

Also, if user has selected 'allow user input' for some attribute parameter values in the config UI, slider controls for those parameters will appear in the widget UI along with the travel mode selection control. The values set by user for these parameters will then add or override the travel mode attribute parameters. Please confirm.

**Comment by MikeMillerGIS** [comment]
I actually think that in the configuration, you have the option to define your own "travel mode"(the current functionality) or select a predefined travel mode.  The new ArcGIS Online travel modes not only have all the settings, but also include the routing service url I believe.  In hindsight, if we knew this was coming, we could have simplified the configuration experience by only supporting these new travel modes. @CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
There is no option to select a pre-defined travel mode in the current config UI. 
Please let us know your thoughts on our proposed approach or if you'd like this implemented differently.

**Comment by MikeMillerGIS** [comment]
I was thinking in the configuration, you have the option to select a travel mode(which will fill out all the NA settings) or define it manually(the current design of the widget)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Are you suggesting that we display the travel modes only in the config UI and not in the widget UI?

The flow of configuring travel mode will be:

1. User sees a dropdown to select travelmode and all NA settings are displayed below it in the config UI
2. The default travel mode is pre-selected and defaults for NA settings are loaded from default travel mode
3. User can select 'Allow user input' for any NA setting and a slider control is displayed for that setting in the widget UI
4. Travel mode selection is not displayed in the widget UI. Only the parameters that are set to 'Allow user input' will be displayed in the widget UI.

Please confirm our understanding.

**Comment by MikeMillerGIS** [comment]
Almost.  In the config, the user has an option of selecting a travel mode or manually configuring the widget(what we have today).  If the user selects a travel mode, none of the NA settings will be exposed.

We can talk through it next week

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

We have outlined our approach and mockup to implement support for travelmodes in Service Feasibility widget. Please let us know your comments.

* User can choose between using travel modes or custom NA settings
* When travel mode is chosen, the NA settings are hidden

![image](https://cloud.githubusercontent.com/assets/2959186/9306555/b408539e-4516-11e5-85f2-e74982015303.png)

![image](https://cloud.githubusercontent.com/assets/2959186/9306562/bc8e6b7a-4516-11e5-9e57-a41d870196ca.png)

**Comment by MikeMillerGIS** [comment]
Yes, this looks good.  But doesn't the travel mode require the defined NA service in the organization?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

* For AGOL closest facility service, the travel mode parameter accepts a JSON object representing travel mode settings. The travel mode settings can be obtained from `GetTravelModes` tool from the Utlities service. This will also return settings for any custom travel mode configured in the Org.
* For Server closest facility service, the travel mode parameter accepts an item ID which can be looked up in `supportedTravelModes` property of the NA service. 
* For appbuilders connected to AGOL, the url to `GetTravelModes` is provided in helperServices>routingUtilities in Org properties. We will be able to list any custom travel mode created in the Organization in this case.
* For appbuilders connected to ArcGIS Portal, the helperServices do not provide routingUtilities. You also cannot create custom travel modes in Portal yet. Thus, only `supportedTravelModes` will be displayed in the dropdown even if you configure an AGOL closest facility service.
  * The option to use travel modes will be disabled for NA services that do not have travel modes setup while publishing.

**Comment by MikeMillerGIS** [comment]
Thank you for the details.  Some good info to know.  I am fine proceeding with the mock ups

**Comment by MikeMillerGIS** [comment]
I cannot get a online service to work, can we walk through this tomorrow?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
When using proxied premium services, we found out that there's been a change in the way ArcGIS Online stores the URL. The service endpoint "ClosestFacility_World" is not saved in the URL anymore, i.e., if you register the URL,  http://route.arcgis.com/arcgis/rest/services/World/ClosestFacility/NAServer/ClosestFacility_World 
the url that gets saved is this, 
http://route.arcgis.com/arcgis/rest/services/World/ClosestFacility/NAServer
i.e., it is saved without the "ClosestFacility_World" endpoint

We confirmed this change by comparing this with a 10.3 and 10.3.1 Portal, which saves the full URL correctly.

The NAServer endpoint returns the list of all ClosestFacilityLayers  
![image](https://cloud.githubusercontent.com/assets/2959186/9986542/a4419a14-605b-11e5-8582-b5dc7432797a.png)

To adapt to this change in AGOL, we propose to display a popup allowing users to select from the list of ClosestFacilityLayers similar to what we have in the election widgets (as shown below). Only in this case, the list would contain closest facility layers instead of route layers.

![image](https://cloud.githubusercontent.com/assets/2959186/9986789/615db720-605e-11e5-82d2-1da375c08c20.png)

If you'd like to continue testing travel modes functionality, you may just append "/ClosestFacility_World" to the URL while configuring for now, till we provide the popup in the next code drop. 

Please let us know your thoughts.

**Comment by MikeMillerGIS** [comment]
Sounds good please proceed

Sent from my Verizon Wireless 4G LTE DROID

**Comment by MikeMillerGIS** [comment]
verified
