### ISSUE TITLE
Network Trace - Legibility with 1.2 Dart/Launchpad Themes

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#236]
@MikeMillerGIS With the Dart Theme, unable to read any of the overview text or headers.
![image](https://cloud.githubusercontent.com/assets/5611508/8989112/e2157fcc-369e-11e5-89f0-03587463d00d.png)
![image](https://cloud.githubusercontent.com/assets/5611508/8989129/042705ea-369f-11e5-85ce-c351d2d1a050.png)

**Comment by pLeBlanc93** [comment]
![vis](https://cloud.githubusercontent.com/assets/12817527/9014688/d63e30e2-3778-11e5-8e81-84d37d548a22.PNG)

Button visibility is also poor for the Launchpad Theme

**Comment by CTLocalGovTeam** [comment]
@clareprice, @pLeBlanc93, @MikeMillerGIS 

We looked at button visibility and found that all buttons in other widgets too look the same, when disabled, for e.g. Draw widget. This is because the launchpad theme has customized the default jimu button style which is used here. Wherever jimu button controls are used, they will acquire this style from launchpad theme. If you change the theme, you will notice that the buttons adapt to style specified in the theme.

We also looked at the legibility of text in results panel in dart theme. This too looks like an issue with the dart theme which sets all text in widget to white color. We are using in built controls (jimu-container) to display the results panel and you will notice it changes according to the theme you have selected. 

Please let us know your thoughts.

**Comment by previnWong** [comment]
@CTLocalGovTeam to get around this, the themes have specific widget overriding css in WAB v1.2.  To keep the changes on the widget side, and not on the theme side, I did the following workaround in another widget to control the font color and other aspects.  (dom Construct and dom Place didn't seem to work)
```
      _setTheme: function() {
        if (this.appConfig.theme.name === "BoxTheme" || this.appConfig.theme.name === "DartTheme" ||
          this.appConfig.theme.name === "LaunchpadTheme") {
            var headText = query("head")[0].innerHTML;
            query("head")[0].innerHTML = headText + "<link rel='stylesheet' href='"+this.folderUrl+"/css/dartTheme.css'>";
        }
      },
```

**Comment by previnWong** [comment]
@CTLocalGovTeam just fyi, the load order is WAB css, widget css, then theme override css.  You can query for the override css class and try and modify it as well.  I couldn't get it work, but worth another look.

**Comment by pLeBlanc93** [comment]
Dart legibility is now great. @previnWong @CTLocalGovTeam if grayed out button on the Launchpad theme can't be overridden, then this can be closed.

**Comment by clareprice** [comment]
@CTLocalGovTeam I am still seeing one issue with the dropdowns when saving a layer.
![image](https://cloud.githubusercontent.com/assets/5611508/9550942/1c284ff2-4d63-11e5-969d-1954a8f8675b.png)

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam Can we make this color a little more inline with the dart theme?  Maybe a shade of gray?
![image](https://cloud.githubusercontent.com/assets/2707285/9962278/dcb1ac06-5df2-11e5-9b29-44da4c22deab.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We can make this a shade of gray similar to the gray background. Would you like the gray font color to implemented only for Dart theme or for all the themes. Currently it is black for all themes.

**Comment by MikeMillerGIS** [comment]
Only the dart theme.

Sent from my Verizon Wireless 4G LTE DROID

**Comment by MikeMillerGIS** [comment]
Still looks like the list does not match the dart theme
![image](https://cloud.githubusercontent.com/assets/2707285/10205030/f928c830-678c-11e5-82a5-3a485f27ab7f.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS ,

This was implemented as per the sample UI guidelines you shared.

![image](https://cloud.githubusercontent.com/assets/2959186/10281666/c06976e2-6b93-11e5-9879-84dbdebc7745.png)

Since all other themes have a white background it matches with the sample. However, for the dart theme due to the dark background, it does not match the styling. If we were to keep the background of the list as per the theme, it would affect the appearance of the icons like 'Save to layer' & 'Export'.

**Comment by MikeMillerGIS** [comment]
Can we make alternative icons for the dart theme so we can color the control appropriately
![download-csvv2](https://cloud.githubusercontent.com/assets/2707285/10282486/30a957c4-6b49-11e5-81b0-8012cb7d0c3a.png)
![download-csvv1](https://cloud.githubusercontent.com/assets/2707285/10282487/30b39e0a-6b49-11e5-8d99-c8c148894e10.png)
![save-layerv1](https://cloud.githubusercontent.com/assets/2707285/10282488/30edb8e2-6b49-11e5-9201-f44ff34e9a54.png)
![save-layerv2](https://cloud.githubusercontent.com/assets/2707285/10282489/316c4fea-6b49-11e5-93bf-2f68f470e12d.png)



?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS ,

We tried your gray icons for both white & dark themes. This is how they render :  

![image](https://cloud.githubusercontent.com/assets/2959186/10303185/79dd86c2-6c2f-11e5-8c73-ebe7cc07159d.png)

If we make the background color as per the theme and change the text color to white it works for the dart theme. Is this what you are looking for?

Should we do the same for the other pages that appear white?
![5](https://cloud.githubusercontent.com/assets/2959186/10303317/856ca382-6c30-11e5-8a22-9c89ac53c83b.PNG)

**Comment by MikeMillerGIS** [comment]
Yes, I think it looks better

**Comment by MikeMillerGIS** [comment]
Can also provide the same overrides for the icons for the dart theme?
![image](https://cloud.githubusercontent.com/assets/2707285/10522712/a3e263b8-7344-11e5-9481-8eca52e75c96.png)

**Comment by MikeMillerGIS** [comment]
verified
