### ISSUE TITLE
Service Feasibility - Controller word wrap

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#243]
WAB - Dev 1.2
![cutoff](https://cloud.githubusercontent.com/assets/12817527/9013892/b4a10e50-3773-11e5-85a0-d65464e79bd0.PNG)

Text is cut-off for when the widget is placed in a box/header controller. The control can't be widened like other themes.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS @pLeBlanc93 

The up/down arrows for sorting can be appropriately positioned to occupy the available space. An ellipsis will be displayed if it exceeds available space.

For labels displayed in top portion of widget, we can display upto two lines and wrap the label at word level instead of character level. However, if we display two lines, then we wont be able to display the ellipsis, the label will just be cut off without an ellipsis.

Can you please confirm if this is ok.

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam 
both items confirmed

**Comment by MikeMillerGIS** [comment]
verified
