### ISSUE TITLE
Image Discovery: request for additional sort and shopping cart features

### ISSUE THREAD

**Issue by danslayback** [Esri/solutions-webappbuilder-widgets#250]
I've been trying to configure the Image Discovery widget for use with searching a large collection of satellite imagery. It would be very helpful if two features could be updated:

**Sort Configuration**: currently this only allows filtering/sorting by cloud cover and date. It would be very helpful if this could be expanded to allow sorting/filtering on any available attributes in the source image service. Or at least a few additional ones.

**Shopping cart**: an option to export the cart to CSV would be very helpful, with all attributes, or at least those that are set to be displayed. We'd also like the ability to turn off the Create Web Map option.

I know the standard Query widget can get around some of these issues, but it has other limitations at present. 

thanks!

**Comment by Rrivera5127** [comment]
Hi Dan, I am working on the shopping cart requests right now and had a quick question. Do you want separate CSV files for each image service you have in your shopping cart? I ask because Image Service 1 might have a field that Image Service 2 does not have. How do you want that handled?

I added the disable web map checkout option to the configuration, I will commit the change when export is complete.

**Comment by Rrivera5127** [comment]
Implemented Export functionality on 9-4

**Comment by danslayback** [comment]
Thanks much for the updates - works great.
