### ISSUE TITLE
Service Feasibility - Business count stuck at 4, no results

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#267]
![image](https://cloud.githubusercontent.com/assets/2707285/9886077/840b3a9c-5bb6-11e5-8044-6c11dfc62d79.png)

**Comment by MikeMillerGIS** [comment]
Same result with new services and map.  Here is the map and service url
http://54.203.249.87:6080/arcgis/rest/services/A4TC/ServiceQualificationRoute/NAServer/Closest%20Facility
http://arcgissolutions.maps.arcgis.com/home/item.html?id=88c4ad70f296485fb837d72a0673790f

**Comment by MikeMillerGIS** [comment]
Can you verify your build number for WAB?  Mine is 2015-08-07_21-49-18_#476 and verified it against the released version.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Our build number for WAB is the same, i.e., `2015-08-07_21-49-18_#476` 

The root cause of this issue is that sometimes, the widget was incorrectly using the first layer in the webmap as the business layer. That's why it was able to fetch the count, but not able to display the list. 
This will be fixed in the upcoming code drop.

**Comment by MikeMillerGIS** [comment]
verified
