### ISSUE TITLE
Service Feasibility - Cannot set Save To Business layer

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#268]
Both layers are points.
![image](https://cloud.githubusercontent.com/assets/2707285/9886126/bc787872-5bb6-11e5-8254-e6c44eaf5300.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
The root cause of this issue is that the geometry type was always being checked against the first layer in the drop down, even if you selected a layer at second or third order in the dropdown.
This will be fixed when we implement issue #225 where we are modifying options to save "Selection Layer".

**Comment by MikeMillerGIS** [comment]
verified
