### ISSUE TITLE
Service Feasibility - retain graphics on error

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#292]
@CTLocalGovTeam  When defining the location on the map, if it pass the desired extend, an error message box appears. When you clear the message, all graphics are cleared.  User has to digitize them over.  The barriers should remain and only needing the user to re-digitize the desired location.

![image](https://cloud.githubusercontent.com/assets/11183838/10496492/f6e68ece-7275-11e5-8f71-03d6c10db6e6.png)

![image](https://cloud.githubusercontent.com/assets/11183838/10496499/03964c90-7276-11e5-8444-05181c93bc60.png)

![image](https://cloud.githubusercontent.com/assets/11183838/10496505/1428cbb4-7276-11e5-9bd2-b884da78aa23.png)

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS 
This behavior is as designed. All drawn graphics are cleared when there is an error. Please let us know if you'd like to change this to retain just the barriers and clear only the location graphic. This will also disable the Find button, since new location has to be defined. Please confirm.

**Comment by MikeMillerGIS** [comment]
I think we should keep the barriers on a error, just remove the flags
