### ISSUE TITLE
511- Python script -HIGH

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#373]
-Ensure configuration experience is in line with the Transportation team approach
-Ensure script updates per Trans team needs
-Incorporate Quantization or Generalize logic to improve performance on load

**Comment by jmhauck** [comment]
The current thought here is that rather than writing the configuration from the widget that we would first instruct the user on the initial publish process. Then in the script we could read the layer definition from the published resources rather than requiring the user to in some way input these values. This would require several additional changes to the script.

**Comment by jessnoo** [comment]
tracking through other issues
