### ISSUE TITLE
511- Core req's

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#376]
-Sanitize calls
-jsLint
-Mobile CSS changes

**Comment by jmhauck** [comment]
Have not started this yet. The width of the panel is not correct on certain form factors and I was thinking we should collapse the main panel icon area. The linting and sanitize calls should be simple to deal with just need to start on them.

**Comment by lindsayking** [comment]
Here is what the widget looks like after commit https://github.com/Esri/solutions-webappbuilder-widgets/commit/913adec87a2f9650e3c7a150791b7a3d9c466a6f.

On an iPhone 6 with and without the attribute table widget activated
![image](https://cloud.githubusercontent.com/assets/4316336/12158353/0e672766-b48e-11e5-969e-6625060a9d01.png)


On an Android phone with and without the attribute table widget activated
![image](https://cloud.githubusercontent.com/assets/4316336/12158555/dbbf8e50-b48f-11e5-9793-d629b44cdd84.png)

I'll look into how other widgets behave when they and the attribute table are opened at the same time.  The 511 widget is difficult to use as-is when the attribute table widget is taking up so much screen real estate.

**Comment by jmhauck** [comment]
@lindsayking I will look some more at other widgets as well but we only have so much space to work with. Please let me know if you have any specific suggestions on how the approach should differ.

**Comment by lindsayking** [comment]
@jmhauck  Looking at how some other widgets behave, I think perhaps we should shy away from attempting to show the 511 widget at the same time as other widgets.  For example, if the attribute table widget is already open when the Legend widget opens, the Legend widget simply displays on top of the Attribute Table widget.

![otherwidgetsoniphone](https://cloud.githubusercontent.com/assets/4316336/12185850/9ded7f88-b552-11e5-9e3f-4c103a994b51.PNG)

Then, if the Legend widget is closed, it disappears and the Attribute Table widget becomes visible again beneath it.  

I think the 511 widget should "bump up" widgets like the scalebar and coordinates widgets, but for other 1/2 screen widgets, it should simply display on top of them.

**Comment by lindsayking** [comment]
@jmhauck   Let's concentrate on consuming the same space with our widget as other widgets like the Legend widget do, and we'll revisit the the surrounds if needed.

**Comment by jmhauck** [comment]
@lindsayking I changed from 40% to 50% as the other widgets do. Also now place the panel relative to the browser rather than the map so the attribute table an our widget would not stack and so we could bump up the location of things like the coordinates that are position based on the map container. This was handled in a similar way as the SA widget. One difference is that we listen for when the map re-sizes. So we can catch that case you mentioned for the SA widget where you could open our widget...see it bump up the other controls... open and close the attribute table would pull those controls back to the bottom. When you go through this workflow now you should see them adjust again to be above our widget.

**Comment by lindsayking** [comment]
Now tracking this issue in devtopia.
