### ISSUE TITLE
CoordinateTool widget DD to MGRS rounding issues?

### ISSUE THREAD

**Issue by jmccausland** [Esri/solutions-webappbuilder-widgets#399]
When you input DD of "40 -121", MGRS converts to 10TFK7072529673.  Checking this with http://www.earthpoint.us/Convert.aspx gives you 10TFK7072529672.  Rounding issue?  Some documentation says to not round up, others do not.

**Comment by migueldls** [comment]
@jmccausland If we are saying that this tool uses the WGS84 datum I think the tool rounding centimeters up is fine. The WGS84 datum to many is described as a reference frame more than a true datum and only accurate to ~1 to ~2 meters. Considering that the tool is still within the 1 meter tolerance do we need to make a change?

**Comment by elinz** [comment]
@jmccausland @migueldls @nfeuerstein Installed the NGA Geotrans 3.7 and tested the same coordinate...
![image](https://cloud.githubusercontent.com/assets/4635490/21368057/8b624202-c6b5-11e6-8aa4-679caa3e98cf.png)

Geotrans also converted the coordinate 40 -121 to 10TFK7072529672, whereas our ArcGIS Pro addin, ArcMap addin and Web AppBuilder widget converts to 10TFK7072529673.

According to @kgonzago the Web AppBuilder widget is using the Geometry service to perform these conversions (http://tasks.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer).

Using the ToGeoCoordinateString endpoint I tested the conversion of this input coordinate. There is a parameter to set rounding. 

With rounding disabled the service returns the same value as Geotrans...
![image](https://cloud.githubusercontent.com/assets/4635490/21370216/84a38b4c-c6bf-11e6-9b6b-dc9d23452f5c.png)
and the online tool specified earlier (http://www.earthpoint.us/Convert.aspx)...
![image](https://cloud.githubusercontent.com/assets/4635490/21370404/51e2da18-c6c0-11e6-9fa4-4f404c4fe778.png)
In the screenshot above, note the UTM centimeter value for northing (i.e. 4429672.97). In this particular case its more accurate to round.

With rounding enabled the service returns the same value as the widget, and ArcMap and ArcGIS Pro addins (and also the identify tool in ArcMap)...
![image](https://cloud.githubusercontent.com/assets/4635490/21370250/abee8332-c6bf-11e6-8d75-d03b1547ab25.png)

@nfeuerstein My recommendation at this point is to leave the widgets and addins alone, i.e. continue to have them round since all three are producing consistent values and as @migueldls stated above you can't get sub-meter accuracy with WGS84. What we may want to do as a future enhancement is to have a configuration button/page for the addins/widgets that would the user to set rounding options, etc, which would be passed to the geometry service or projection engine to further refine how the conversion is made. Please advise how you want to proceed. Thank you.

**Comment by nfeuerstein** [comment]
@kgonzago @elinz can the geometry service be easily configured to point elsewhere?  If you use this widget on an air-gapped network (zero connection to the www) will it fail since its pointing to an AGO geometry service?

**Comment by elinz** [comment]
@nfeuerstein @kgonzago The web app containing the widget can be re-configured to point to an internal geometry service, which @Dbarnes1 tested the other week when testing the GRG widget.

**Comment by nfeuerstein** [comment]
In that case, I agree with your recommendation.  Leave it alone and we can entertain a future enhancement for configure rounding options.

**Comment by elinz** [comment]
@nfeuerstein @kgonzago FYI. Here is a blog, which explains how to configure a web appbuilder app in a disconnected enviroment... https://blogs.esri.com/esri/arcgis/2016/11/02/deploying-web-appbuilder-for-arcgis-developer-edition-in-a-disconnected-portal-for-arcgis-environment/

**Comment by elinz** [comment]
@nfeuerstein If it's ok with you, I'll go ahead and change the milestone to after next and change the label to an enhancement.

**Comment by nfeuerstein** [comment]
Sounds good @elinz

**Comment by topowright** [comment]
This is still an issue and needs to be moved to the new repo. Here is a screen capture of the issue using the updated widget: 
![image](https://user-images.githubusercontent.com/5488313/30294835-5be44520-96f3-11e7-90a3-06b87d2452a5.png)

**Comment by topowright** [comment]
This issue has been moved.
