### ISSUE TITLE
Enhanced Editor - Trim not nullable fields prior to loading to Attribute Inspector

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#443]
To trigger field validation by the attribute inspector, remove the blank space added to the template

**Comment by camtran** [comment]
@MikeMillerGIS Removing the blank space in the template itself won't trigger field validation.  In order to have the field validation work, I performed the followings:
- Remove the blank space in the template,
- When the validation/submit button is click, find the required fields that are not valid and trigger focus/loose focus events 
- I also append a red asterisk to the labels of those required fields.

**Comment by MikeMillerGIS** [comment]
verified
