### ISSUE TITLE
Smart Editor - Allow a user to select a field at runtime to sticky or add to the preset fields

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#455]
Similar to the concept as Survey 123 as save as favorites

Request was once I create a feature, can I use the same values for the next feature.  This workflow is supported is collector.  So one thought was to allow the user to sticky fields and move them to the preset list

**Comment by previnWong** [comment]
A workflow for this could be the following.  If you have a person inspecting trees.  A field like "isFireZone" might not be a preset field and has no need to be.  But since he/she is working in a known fire area today or if it's fire season, they could runtime, add the field "isFireZone" and set it "Yes" for their daily work.

**Comment by camtran** [comment]
Thanks for providing a sample workflow. It helps a lot :+1:
