### ISSUE TITLE
Network Trace - Results Pop-up

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#498]
### Bug
When selecting a result pop-up in the map, short integer domain fields return only the coded value domain rather than the description value. For example, Owned by field is return with -1 rather than "Utility"
![image](https://cloud.githubusercontent.com/assets/5611508/14332028/ac56ea14-fbfc-11e5-8258-9250a5199dd8.png)

### Repo Steps or Enhancement details
Configure the widget and perform an isolation trace, select a graphic on the map (for example, isolated customers) to view the pop-up. The pop-up only returns the short integer value.

@MikeMillerGIS

**Comment by MikeMillerGIS** [comment]
If this is the graphics and not once you save, it is a known issue as the gp result as a feature set is unaware of domains.  Can we mark as known issue?

Sent from my Verizon Wireless 4G LTE DROID
On Apr 6, 2016 4:39 PM, Clare Price <notifications@github.com> wrote:
Network Trace
Version in master branch
Bug

When selecting a result pop-up in the map, short integer domain fields return only the coded value domain rather than the description value. For example, Owned by field is return with -1 rather than "Utility"
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_5611508_14332028_ac56ea14-2Dfbfc-2D11e5-2D8258-2D9250a5199dd8.png&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=hoBw6CQuytVR65zzd5i-Zw&m=encXn-CqK2kI6k7BbNbYAC_0jPh3kGieYHAmr1--tL4&s=0MA99s0a0PMhUvv6LTKAUVhjy4j5TZ47VA8B5NEQ9-0&e=>

Repo Steps or Enhancement details

Configure the widget and perform an isolation trace, select a graphic on the map (for example, isolated customers) to view the pop-up. The pop-up only returns the short integer value.

@MikeMillerGIS<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_MikeMillerGIS&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=hoBw6CQuytVR65zzd5i-Zw&m=encXn-CqK2kI6k7BbNbYAC_0jPh3kGieYHAmr1--tL4&s=7lo3m1-Ufwu_h8KU-iGSySHiPbNqulUf02aHHdS38Co&e=>

**Comment by clareprice** [comment]
@MikeMillerGIS Thanks for the info! Will close this as it is a known issue. Where are we documenting these known issues, might be a nice to have on the solutions page with things like hydrant valves need to be a separate layer, this, etc...
