### ISSUE TITLE
Smart Editing - Disabled Editable Fields

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#507]
### Widget
Smart Editor
### Version of widget
1.0 Alpha
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
Currently, if you turn off editing on a field, it is visible.  Should we remove it?  Also if you set it up for a preset, the value is applied and you cannot change it.  What should we do here?

@allisonmuise @camtran @previnWong 
![image](https://cloud.githubusercontent.com/assets/2707285/14440567/74bfcf7a-fffe-11e5-88c2-0b0a2a5d57f6.png)

![image](https://cloud.githubusercontent.com/assets/2707285/14440544/562c49bc-fffe-11e5-93cb-1404945c1106.png)

**Comment by allisonmuise** [comment]
IMO, preset values should be editable if the field is editable in the popup settings. 

For reporter, manager, and polling we only show editable fields in editing mode.

**Comment by MikeMillerGIS** [comment]
The field is not editable according to the widget config, hence be disabled in the attribute inspector.

Option 1:
  Leave as is, non editable fields can be preset using the preset values

Option 2:  
  Hide non editable fields, still calculated if set to preset

Option 3:  
  Hide non editable fields, they are not preset

Option 4??

**Comment by previnWong** [comment]
IMO, the field should NOT be available as a preset in settings, so no preset ability.  It should remain in the attribute inspector table but field should be disabled.  We should not hide it because a user might need to know the value of it for entry into another editable field. (in edit feature case, and new feature case if it has a default value)
