### ISSUE TITLE
GeoLookup widget - use without a polygon layer

### ISSUE THREAD

**Issue by ghcch** [Esri/solutions-webappbuilder-widgets#56]
Sometimes it may be good to have the flexibility to only plot the csv points without doing the point in polygon processing.  Currently it seems the widget only works if there is a polygon layer present.  This may be useful to a lot of users just to simply plot points from a csv.

**Comment by MikeMillerGIS** [comment]
@previnWong Do you want to look at adding this option?

**Comment by previnWong** [comment]
solution to add checkbox to widget to bypass all enrichment and just plot points.  then just validate determine whether or not to call 
```
this._enrichData(this.featureLayer);
```

**Comment by MikeMillerGIS** [comment]
That works for me, we probably need to page out the config so if the user does not choose to enrich against polygons, those config pages are hidden

**Comment by previnWong** [comment]
I would leave the config pages since an "admin" or IT guy would most likely be setting this widget up.  The checkbox is more for the end users.  One scenario I can see is that an user might want to check and verify if all the points are in the right location before they geolookup.  Like a pre-check,

**Comment by MikeMillerGIS** [comment]
ok, go with it.
