### ISSUE TITLE
Map Filter - Ability to search for text string containing special characters ( & , ' th . @) 

### ISSUE THREAD

**Issue by WalterPotts** [Esri/solutions-webappbuilder-widgets#562]
Example strings: 
Farmer's Market
St. Patrick's Day Parade
30th Annual Riverwalk Fine Art Fair
Naperville Half Marathon & Marathon

**Comment by pLeBlanc93** [comment]
@previnWong, support for single quotes is straightforward since they just need to be escaped with another single quote.
`&<>` is trickier because `utils.sanitizeHTML()` replaces them with their respective escape characters. I checked all the characters from [here](http://www.theukwebdesigncompany.com/articles/entity-escape-characters.php) and those appear to be the only ones (```™€!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſ```)

What's your thoughts? Remapping after sanitizing won't work because, in theory, someone might want to filter by `&amp;`.

**Comment by MikeMillerGIS** [comment]
Could use html/Encode and decode from dojox

**Comment by previnWong** [comment]
implemented fix from @pLeBlanc93 .  @WalterPotts please check and see if it fixes your issues.  FYI, the widget is called "GroupFilter" now.  Close issue if it does.

**Comment by WalterPotts** [comment]
Works great - thank you.
