### ISSUE TITLE
swipe tool widget window gets in the way of using the actual tool

### ISSUE THREAD

**Issue by jgravois** [Esri/solutions-webappbuilder-widgets#60]
it would be nice to be able to minimize or close the swipe widget's configuration dialog and continue to use the tool.  currently, closing the window turns off the widget entirely.

this problem does not affect small form factors because an additional 'minimize' icon appears which allows you to suppress the configuration dialog and continue swiping.

this is not a show stopper, more of a 'nice to have'

**Comment by kgonzago** [comment]
@jgravois The swipe widget does work if the widget is minimized (tested in desktop browser). Have you noticed the functionality not working once the widget is minimized?

You are correct once the widget is closed, the swipe tool no longer works. The swipe functionality will need to be a tool rather than a widget and will require extensive work.

**Comment by jgravois** [comment]
yeah, it definitely seems inappropriate to me that the toolbar has to be open to use the tool.

**Comment by kgonzago** [comment]
I'd like to have it still be a widget. Swipe function needs to be present once widget panel is closed. Let me test a few things.

**Comment by jgravois** [comment]
:+1:
