### ISSUE TITLE
Service Feasibility Code Review

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#68]
Only pertaining to the widget code.  Settings code not complete at time of 2/26/2015 delivery.  Comments to address Sprint 1.

No need for xhr request object to get config file.  Widget framework already provides access to it with this.config. (line 92)
            startup: function () {
                //Accessing config.json file and creating dojo global variable.
                xhr("widgets/ServiceFeasibility/config.json", {
                    handleAs: "json"
                }).then(lang.hitch(this, function (data) {
                    this.configData = data;
                    this._initializingNetworkAnalysisServiceData();
                    this._initializingJimuTabContainer();

Not sure which config this is referring to, the Theme’s config?  (line 150)
            _accessGeometryService: function () {
                xhr("config.json", {
                    handleAs: "json"
                }).then(lang.hitch(this, function (data) {
                    this.outsideConfigData = data;

Keep event registration consistent (line 301).
                on(dijit.byId(attributeParameterValue.name + "Slider"), "change", lang.hitch(this, function (value) {
                    dom.byId(attributeParameterValue.name).value = value;
                }));
                textbox.on("change", lang.hitch(this, function () {
                    if (parseFloat(textbox.value) <= maxValue) {
                        dijit.byId(attributeParameterValue.name + "Slider").attr("value", textbox.value);
                    }
                }));

Avoid “dojo.”, use alias. (line 348, 663, 822, 851)
                txtboxCount = dojo.query(".txtboxParamValue");
                dropDownCount = dojo.query(".dropDownBusinessValues");

Consider using a helper function to handle geometry type clicked instead of repeating same code multiple times. (lines 368 to 539)
_onPointBarrierClicked: function () {
_onPolylineBarrierClicked: function () {
_onPolygonBarrierClicked: function () {
_onSelectLocationClicked: function () {

Should barrier symbols be a config file item?
                pointBarrierSymbol = new SimpleMarkerSymbol(esri.symbol.SimpleMarkerSymbol.STYLE_SQUARE, 10,
                                 new esri.symbol.SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_SOLID,
                                 new esri.Color([255, 0, 0]), 1),
                                 new esri.Color([0, 255, 0, 0.25]));
                polylineBarrierSymbol = new SimpleLineSymbol(esri.symbol.SimpleLineSymbol.STYLE_DASH,
                                    new esri.Color([255, 0, 0]), 3);
                polygonBarrierSymbol = new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID,
                                   new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID, new Color([0, 0, 0]), 2),
                                   new Color([0, 0, 255, 0.5]));

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS Following are our response:

1. No need for xhr request object to get config file. Widget framework already provides access to it with this.config. (line 92)
**CyberTech response**: *We will implement this in Sprint 2*

2. Not sure which config this is referring to, the Theme’s config? (line 150)
**CyberTech response**: *-	The config here refers to the application config. On widget launch, we are checking if the application config has a Geometry Service URL. If Geometry Service URL is not found, then user is shown an error message. We are doing this because the widget cannot run without a Geometry Service*

3. Keep event registration consistent (line 301).
**CyberTech response**: *We will implement this in Sprint 2*

4. Avoid “dojo.”, use alias. (line 348, 663, 822, 851)
**CyberTech response**: *We will implement this in Sprint 2*

5. Consider using a helper function to handle geometry type clicked instead of repeating same code multiple times. (lines 368 to 539)
**CyberTech response**: *We will implement this in Sprint 2*

6. Should barrier symbols be a config file item?
**CyberTech response**: *The previous application on tryitlive server had all the symbologies hardcoded in the codebase. We had planned to make the symbologies configurable using config UI as part of Sprint 2, where integration of config UI and widget is planned. However, for sprint 1, we have implemented the approach as followed in tryitlive URL*

**Comment by previnWong** [comment]
I also found two more I wanted to share after the initial post

Use alias instead of esri.task.QueryTask, you already have the alias defined. (Line 756, 557)
```
queryTask = new esri.tasks.QueryTask(url);
```
arcgis api uses a callback as a parameter of queryTask.  You can check the status with the “on” event.  The “then” is a promise that I don’t think QueryTask needs. Although "then" probably works, users looking to extend this widget, will reference the api page and see that it is looking for "on complete" event.  They will not see "Then" in the api reference and will have to know about the promise concept.  (Line 757).  
```
queryDeferred = queryTask.execute(queryFeature);
 queryDeferred.then(lang.hitch(this, function (results) {
```

In general, for callbacks, if the inline function is long winded, break it out into a separate function.
