### ISSUE TITLE
Network Trace - Config Panel - Output Params

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#74]
Clicking tab when the cursor is in the Label input box moves the cursor to the summary text box, not the skippable checkbox.

**Comment by MikeMillerGIS** [comment]
tabbing also skips the other checkbox on the form

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are analyzing this and will update you soon

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are still investigating on approach to implement this.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have analyzed this issue and found that this is the default behavior of 'jimu/dijit/CheckBox'.

This is the same behavior observed in Geoprocessing widget. When we use 'dijit/form/CheckBox' instead of 'jimu/dijit/CheckBox', then tabbing from textbox moves the control to checkbox.

If we opt to use 'dijit/form/CheckBox, then we have to rewrite event handling part, which is a bit different for both the resources. 

Please advise.

**Comment by MikeMillerGIS** [comment]
We can defer the issue now.  I will log a bug on the jimu check box

**Comment by MikeMillerGIS** [comment]
not a widget issue
