### ISSUE TITLE
Network Trace - Trace Not Clearing

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#76]
Steps to Repo

In Builder Mode
Run Trace
Open the config panel for the widget
Change some settings and save
Widget will refresh, but graphics remain on the screen

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are analyzing this and will update soon

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are observing this issue when we view the widget in the configuration screen itself. However, the widget works fine when we view the widget in new tab by clicking on Launch button at the bottom left corner of the configuration screen. We are trying to find out the root cause for this behavior and will keep you posted on the same.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have fixed this issue and will be delivered this in the upcoming release.

**Comment by MikeMillerGIS** [comment]
verified
