### ISSUE TITLE
Distance and Direction WAB widget: Line bearing and distance not updated with manual input

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#760]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

If you create a line by manually by entering a start coordinate and end coordinate the line draws but the length and bearing values do not update and the label displays incorrect values

![1](https://cloud.githubusercontent.com/assets/3740334/21807929/e4d8dc18-d738-11e6-8422-bc2c592afee5.png)

### Repo Steps or Enhancement details

navigate to lines tab
enter specific coordinate pair as start point (1, 1) and click enter.
enter specific coordinate pair as end point (5, 5) and click enter.
Line is drawn but label incorrect

**Comment by adgiles** [comment]
@kgonzago @elinz 

Bug fixed can somebody do an independent check

**Comment by elinz** [comment]
@adgiles @kgonzago Tested the fix on build 11 Jan 2017 09:51 of the widget. This issue is only half fixed. According to "Bug or Enhancement" statement about: "If you create a line by manually by entering a start coordinate and end coordinate the line draws **_but the length and bearing values do not update and the label displays incorrect values_**"

Repo steps:
1. Length unit set to Kilometers; Angle unit set to Mils
2. Enter specific coordinate pair as start point (1, 1) and click enter.
3. Enter specific coordinate pair as end point (5, 5) and click enter.
Result: the labels on the map are updated to display length, length units, angle and angle units, but the Length and Angle text boxes are not updated...
![image](https://cloud.githubusercontent.com/assets/4635490/21863279/a7870b50-d7f1-11e6-94f4-7b6e8e4aac3b.png)

In comparison, when you interact with the map to set the start and end points the labels are updated as well as the text boxes...
![image](https://cloud.githubusercontent.com/assets/4635490/21863324/d35bba82-d7f1-11e6-80f3-83c08ec389da.png)

Reassigning to @adgiles

**Comment by adgiles** [comment]
@elinz

 fixed please verify

**Comment by elinz** [comment]
@adgiles @kgonzago Verified fixed in build 12 Jan 05:50. Both the labels and the textboxes are being updated. Closing issue
