### ISSUE TITLE
Distance and Direction: can't specify 0, 0 in any textboxes that accept a coordinate

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#775]
### Widget
Distance and Direction
### Version of widget
build 11 Jan 2017 09:51
### Bug or Enhancement
The CenterStart/End Point textboxes on the Lines, Circle, Ellipse, and Rings tools do not allow the user to enter the coordinate 0, 0. This is a valid coordinate and the widget should allow the user to enter this coordinate. The Pro and ArcMap addins allow the user to enter 0, 0.

**Comment by adgiles** [comment]
@elinz 

The issue was occurring because the code has a check to see if the coordinate array (which is multi dimensional) has values in it and the first one exists:  

if (r.length <= 0 || !r[0][0]) 

the code was interpreting the value 0 as false, so I added and extra check for a value of 0

if (r.length <= 0 || (!r[0][0] && r[0][0] != 0))

**Comment by elinz** [comment]
@adgiles Verified that this has been fixed in build 12 Jan 09:50. Tested all the tools (Lines, Circles, Ellipses, Rings) and all the controls on the tools and they all accept 0, 0 as a valid coordinate and I can draw graphics based on this coordinate. Closing issue.
