### ISSUE TITLE
Extend the Editor Widget or Edit with a Pop-up

### ISSUE THREAD

**Issue by scottlehto** [Esri/solutions-webappbuilder-widgets#859]
### Bug or Enhancement

     I'm new to developing in WebApp builder and dojo/javascript so please excuse me if I am off base. But I am looking for some information or a sample that someone has extended the edit widget or the smart editor widget. I am just really confused that I don't see this out there. I would just think that this would be a super common thing to do but I must have it way wrong.
         I like the edit widget but it has issues when I try to customize it. I cant seem to change the textboxes to comboboxes and filtering boxes. I cant seem to do it in the popup options either. Anyone been down this road?

**Comment by kgonzago** [comment]
@scottlehto Thanks for your question. This repo contains custom widgets for the WAB. Your question pertains to the edit and smart editor widgets that are part of the core offering of widgets in WAB. If you feel that documentation or samples are lacking, please provide your feedback through https://geonet.esri.com/. The WAB dev team is always looking for feedback.

So, changing textboxes to either comboboxes or filetering boxes will also change the behavior of the edit widget, and it's not a common thing or maybe I haven't come across folks that would want to change, for example, those controls. Regardless, with WAB Developer Edition, you have the code for these dijits and can hack away at the templates associated with them. Also, since you're new to WAB, these links may be helpful:
https://www.sitepen.com/blog/2013/05/15/faq-edit-widget-template/
http://stackoverflow.com/questions/17266438/dojo-inheriting-extending-templated-widgets-how-to
https://developers.arcgis.com/javascript/3/jshelp/intro_custom_dijit.html

The WAB dev team also provided coding samples that you may find beneficial:
https://developers.arcgis.com/web-appbuilder/sample-code/
