### ISSUE TITLE
Add MGRS coordinates as an option to GRG Widget

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#867]
### Widget
GRG Widget

### Version of widget
2.0

### Enhancement
Add MGRS coordinates as an option for labeling cells in the grid.

**Comment by adgiles** [comment]
@kgonzago can you confirm which part of the grid the MGRS value will be taken from - Center / Bottom Left?

**Comment by kgonzago** [comment]
@kAilshie We are looking into adding MGRS coordinates for the GRG widget. Since this enhancement came from your customer, can you provide some insight to @adgiles's question?

**Comment by kAilshie** [comment]
@kgonzago  I don't know that answer to that specific question but I reached out to my POC and I will relay any information I get back to you.

**Comment by joebayles** [comment]
I would assume they mean like this:
![image](https://cloud.githubusercontent.com/assets/5016557/26020630/b635a8d4-3735-11e7-9425-475efc470eb2.png)

So, I think it would probably be easier to create the GRG from the Grid Overlay widget, since an MGRS GRG goes counter to identifying your cell size, rotation, etc.

It would be like identifying the extent and the level of accuracy (4, 6, 8, 10 digits) and hitting OK.

If they just want to see what the coordinate is for the individual GRG grid square, they can use the Coordinate widget and select an MGRS output (red arrow above).

**Comment by nfeuerstein** [comment]
So, after some research, is been confirmed that customers want to use MGRS/USNG as an analysis mask, so not just as graphic overlay and not just for positioning/navigation. Part of that workflow is being able to create a GRG FROM the USNG/MGRS. For instance, if I was operating on the north side of Redlands, I'd want to choose the extent of that MGRS grid and create a feature for analytics - spatial joins, aggregation polygon, hot spots, etc. The extent of the AOI will help the user determine the size of the grid, large areas may use 1000km grids while small areas may want 100m grids. The benefit of MGRS/USNG is that it's not a temporary/arbitrary grid...it's a standard. Here's a poster that describes some of the use in more detail: https://www.dropbox.com/s/w8kesxwlal6y640/Shawnee%20USGIF%20Poster_v2.pdf?dl=0

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/solutions-grg-widget#3
