### ISSUE TITLE
GRG Widget: Add Coordinate Input Control for setting GRG from Point

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#879]
**Widget**

Visibility Widget

**Version of widget**

All Versions

**Bug or Enhancement**

For consistency across widgets a user should be able to input an a point using the coordinate control as per the distance & direction and coordinate conversion widgets.

**Comment by adgiles** [comment]
Address in PR #883 

Please can somebody verify

**Comment by nfeuerstein** [comment]
Needs to be verified, but removing the verify tag because it's confusing the waffleboard experience. We should probably look into that.

**Comment by NatalieCampos** [comment]
@adgiles i tried to test this but was unable to.  The error i get is below.  I am most concerned about the GRG name NOT being blank because i get a warning for having it blank.  Am I using the widget wrong?

![image](https://user-images.githubusercontent.com/5116835/27103857-f79aff82-503e-11e7-94b0-ddb1d4b846e7.png)

This is the error i get when i leave the name blank...

![image](https://user-images.githubusercontent.com/5116835/27103879-12dbee28-503f-11e7-93dd-54f2e32fa425.png)

**Comment by adgiles** [comment]
@NatalieCampos 

I cannot replicate the error you are seeing above. How are you creating the center point, is it a copy and paste of the value 19.4326° N, 99.1332° W? If so, you must hit enter after pasting the value in for it to be validated and the point drawn. The map should also pan to the correct location.

From the screenshot above it doesn't look like the map has panned over to the US?

In addition there is a check that prevents the user from drawing a grid with more than 2000 cells, so 50x50 should throw another warning:

![untitled](https://user-images.githubusercontent.com/3740334/27126690-38f1d684-50f0-11e7-8861-a8d6aaad529a.png)

**Comment by NatalieCampos** [comment]
Thank you @adgiles my error was related to not hitting enter.  This will have to be addressed with documentation when it is a higher priority.

**Comment by Dbarnes1** [comment]
I'm able to verify that this works, and I added a statement in the documentation "alternatively, paste a coordinate location into the prompt and click enter to mark your center point" Closing.
