### ISSUE TITLE
Distance and Direction widget returns confusing values

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#897]
### Bug
 When using the Distance Calculator weird values are returned. If your time is three hours and your rate is 70 miles/hour, I would expect for value for the radius to be returned as 210 miles. Instead the value being returned for miles is 209.9994. Spoke a bit with @kgonzago about what is going on. I believe what is happening is that we are drawing a geodetic circle, then from the circle, measuring what the radius is, and returning that value, So it ends up being slightly off. In ArcMap this does not happen, and you get back a value of 210. 

![image](https://user-images.githubusercontent.com/5322669/27106115-e1b4a38c-5046-11e7-8b81-61fc7237a51b.png)

**Comment by adgiles** [comment]
@dfoll @kgonzago 

It is nothing to do with geodesic measurements the issue was fair simpler.

All the distances are calculated by converting from the input unit of measure to meters than back to the unit of measure required. It was done this way so you only have to put the formulas in for the number of units of measure x2 (ie. to meters and from meters). Otherwise you would have to do the calculations for every unit of measure to every other unit of measure which would require a bigger effort every time a new unit of measure is added.

The issue was that the number of decimal places used between meters and miles was insufficient, i.e:

miles to meters was 1609.34 and should have been 1609.344
meters to miles was 0.000621371 and should have been 0.000621371192

I have updated these value and all is good for you example above. @dfoll Can you please verify

**Comment by dfoll** [comment]
closing
