### ISSUE TITLE
Smart Editor - Editing Related Records of Existing Features

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#929]
### Widget
Smart Editor
### Version of widget
2.5
###  Enhancement
On editing an existing feature, if there are related records
- [ ] Related Records section will be collapse/expandable for UI space management
- [ ] Have a drop down for each related table (nested if a related table has another related table to it)
- [ ] Have navigation arrow to cycle through the related records
- [ ] Form fields will have smart form capabilities as well in the related table attributes as well as acted upon from or to parent.
- [ ] Ability to delete current record.
- [ ] Ability to add a record (use global id from parent feature)
- [ ] Feature action on pop up to launch Smart Editor in Attribute pane already
- [ ] (optional) Actions in parent feature can cause automatic creation of related record

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS 

For this ticket, we have prepared a mockup (image attached below):

**Left Image:** When a user creates/updates any feature, this screen will be displayed. The first accordion will show the layer in which feature is created followed by related layers/tables. "Back" button is repositioned to the bottom of the screen (not scrollable)
**Center-Left Image:** When a user collapses the layer accordion. All the related layers/tables accordion will be displayed.
**Center-Right Image:** When a user expands a related table accordion, it will show related records (blank fields if a new feature is created). Navigation arrows at the top, 3 buttons ("Add new", "Delete" and "Save") at the bottom. Nested layers/tables will be displayed in the dropdown. When a user selects a nested layer and it has another related table then the second dropdown will be displayed followed by "Go" button. 
**Right Image:** Clicking on "Go" button will display the last screen to add/edit records in nested layers/tables. 

Please let us know your thoughts.

![image](https://user-images.githubusercontent.com/2959186/29965353-de4aa412-8f2a-11e7-82f0-878dcf36cd36.png)

Moreover, we have following questions:

> Form fields will have smart form capabilities as well in the related table attributes as well as acted upon from or to parent.

In the current version of the widget, we have smart form capability ("Hide", "Required" and "Disable") in the layers only (tables are not displayed in config).  So do we have to add the support so that the user can apply those settings?

>Ability to add a record (use global id from parent feature)

Do we have to use only GlobalID or the "keyField" as described in the REST end to add a new record?
![image](https://user-images.githubusercontent.com/2959186/29966116-0e4adf1c-8f2e-11e7-9c26-d18901190ee5.png)

> (optional) Actions in parent feature can cause automatic creation of related record

To create a related record, we need data to fill the fields of the table. We are thinking to use feature template (only if available) otherwise we create a record just by using "keyField"/"GlobalID". Is this approach okay to proceed?

**Comment by previnWong** [comment]
@CTLocalGovTeam the distinct between feature and related item looks too similar in LEFT and CENTER-LEFT images. I think we need an icon, a different accordian or something else to distinguish between feature and related item.  CENTER-RIGHT and RIGHT.  Feature with related items as drop down list.

Yes, please add the new record using the keyField in the REST.

**Comment by MikeMillerGIS** [comment]
![image](https://user-images.githubusercontent.com/2707285/30489143-6feb22e6-9a04-11e7-8dab-54715c51369d.png)

**Comment by MikeMillerGIS** [comment]
- User cannot create new related features
- User can view both related features and records
