### ISSUE TITLE
ERG Widget "Ammonia, anhydrous" throws a GP service error.

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#961]
### Widget
ERG

### Version of widget
2.0

### Bug or Enhancement
BUG

### Repo Steps or Enhancement details
Use "AMMONIA" for "Large" spills and the GP service returns "ERG Geoprocessing status: Failed".

**Comment by joebayles** [comment]
This is using the old values, right?

**Comment by kgonzago** [comment]
@joebayles Tested using the current version of the widget which references the new values.

**Comment by joebayles** [comment]
In the latest data table, I see 

Guide # | ID # | Material Name
-- | -- | --
125 | 1005 | Ammonia, anhydrous
125 | 1005 | Anhydrous ammonia
125 | 3318 | Ammonia solution, with more than 50% Ammonia

No mention of AMMONIA.

Also, I think we can remove one of the anhydrous ammonia since they are the same.

**Comment by kgonzago** [comment]
Thanks @joebayles.

My mistake. It was tested using "Ammonia, anhydrous" value. I'll remove it and check the python script on why it was throwing that error.

**Comment by kgonzago** [comment]
@elinz FYI

**Comment by csmoore** [comment]
This issue was moved to ArcGIS/defense-solutions-proofs-of-concept#1
