### ISSUE TITLE
Address Information - High

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#976]
- All views should reflect address information and allow for updates to the address informtiona

- When a feature is manually moved or when the user alters the address they should have a way to update the feature information shown on the map
 
- The address fields should be tied to target fields to accurately reflect the correct/altered address information when submitting to the service. 
 
- If the address fields are not exposed to submit to, the geometry shape will still be updated to reflect the modified location. 

FYI @jessnoo  @jmhauck

**Comment by jessnoo** [comment]
@jmhauck I believe this issue was the target of today's pull request and we are still missing one aspect: 

- if Target fields match the fields used for locating the item, there needs to be a way to push those changes (either manual changes from the user or reverse geocode changes) up to the Field information - that's not there yet.

Recommend adding a 'persist changes' button next to the Review Location Information header with behavior like:
- disabled if not editing. 
- disabled if no edits yet
- enabled when the location has changed -- either the user corrected the address and pushed the locate button, or the user moved the point on the map and the fields now contain reverse geocode information
- pushing the button copies values up into the Field information for any fields that participate in both sections

![image](https://user-images.githubusercontent.com/6181441/32971017-3fed7328-cba0-11e7-9864-37aece9315a6.png)

**Comment by jmhauck** [comment]
layout use cases that we want or should discuss supporting and how they will look when implemented.

**Comment by jmhauck** [comment]
**Use case:**
_I have modified the location information that originated from the file and generated a new location by using the locate button or by manually editing one of the staged features. I would like to be able to persist this new location information in the configured destination layer fields in addition to persisting the actual geometry that has been generated._

**Main hurdle:**
The widget stores location information and field information separately and does not currently have anything that would represent how they are related to one another.

**Discussion topics:**
Need to understand the relationship between the location fields and associated destination layer fields so we know how to handle the updates.
Need to have a mechanism that will control when this update occurs rather than have it occur automatically. 

**Considerations:**
The destination layer schema requires address information to be stored in a different way than how the address information was provided. For example, the layer stores address data in multiple fields but the address information in the file is in a single field or vice versa.

**Comment by jmhauck** [comment]
After speaking with @jessnoo some more on this a potential option is:

Only allow this behavior when they choose the same field for the locate and field options at runtime. For example, I have chosen the FULADDR field to be used from the file for the “Address” field in the destination layer I have also chosen the FULLADDR field for the location options that will be used to generate the locations. This would require no additional config settings. 

Will still require something that will trigger when the synchronization between the updated location information and field information occurs. The option discussed was like her comment on Nov. 17th. We would have a button that they could click to push the new location value to the field values.

**Comment by jmhauck** [comment]
An additional way that we could consider for when to sync the updates rather than on a button click after locate or edit/reverse geocode is to show a message after one of these actions have occurred so they could just click yes/no directly after rather than see that the sync button has enabled and then click it.

**Comment by jmhauck** [comment]
After the calls we make to the locator to generate a location from an address or generate an address from a location each locator returns not only the location but also the parsed address elements and single line representation of the address or location that is being evaluated.

If we decide to go down a path that would support the consideration of “_destination layer schema requires address information to be stored in a different way than how the address information was provided_” the best way forward that I see is as follows:

Update the config experience to support the definition of this relationship. For example, currently to configure the single field location settings the dialog looks like this:

![image](https://user-images.githubusercontent.com/2170893/34503109-fc0361d8-efd3-11e7-86f2-824e02166ffd.png)

It could be updated to something like this where the inital definition looks pretty much the same:

![image](https://user-images.githubusercontent.com/2170893/34503189-5bd63c8e-efd4-11e7-877a-8fea828e2cb1.png)

Then on the next tab it would allow you to create the required relationship information based on the layer fields and the fields that will be returned from the calls we make to the locator:

![image](https://user-images.githubusercontent.com/2170893/34503253-96c74856-efd4-11e7-87d1-b3a44650df88.png)

**Comment by jmhauck** [comment]
@jessnoo could you take a look at this? It is implemented with the sync button idea we discussed.

**Comment by NikkiGolding** [comment]
@jmhauck  I want to be sure I understand the above notes. In the commit referenced above, the only way the address information gets persisted once moved is under the following conditions:

1. The address information needs to configured as editable in the Source and Destination information and is subsequently presented in the UI
2. The address fields need to named the EXACT SAME WAy
3. The location information, once updated then has to be 'synced' using a button in the UI
4. A save operation persists the information to the feature collection. 


Is this correct?

**Comment by jmhauck** [comment]
Yes, a field to store address information would need to be configured initially as one of the fields made available for the destination layer field information.

Support for the sync capability is not otherwise controlled by the initial widget configuration. It's controlled based on the fields selected at runtime by the end user. The sync button will only enable when the end user chooses the same field from the csv for one of the fields defined in "Location Information" and "Field Information" prior to adding the features to the map. 

For 3 and 4 yes that is correct. After a location has been moved either by click and drag or through the use of the locate button the sync button will enable and allow the values to be pushed from the location review section to the attribute field review section and would only persist if they click save.

**Comment by NikkiGolding** [comment]
@jmhauck regarding 2 in my list above.  Is this correct?

**Comment by jmhauck** [comment]
@NikkiGolding The same field from the users file must be chosen for a location field and an attribute field at runtime. So they would have the same name. But I want to make sure that you were not expecting to need to set any of the names you can configure up front to be the same.

**Comment by NikkiGolding** [comment]
Verified fundamental requirements are met
