### ISSUE TITLE
Evaluate Duplicate Information/Features - High

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#977]
**workflows**

- [x]  Feature is a duplicate and the user wants use the existing feature without changes
- [x]  Feature is a duplicate and the user wants to make changes to the existing feature (update existing feature's location or attribution)
- [x]  Feature is NOT a duplicate > moves into normal review but the feature needs to be geocoded first to ensure a valid location can be found.  If valid location - treated as normal feature feature review.  if no valid location - treated as location not found workflow

**UI Feedback** 

- [x] -Initially, a  feature and supporting attribute  information is presented  to the user. The user is given an option to indicate if the feature is a duplicate using a flag . 
- [x] Actions will support geocoding (reverse as well), 
- [x]  Attribute selection will be presented in pull downs ('use file, use original information')
- [x]  UI Text should be updated to reflect text discussed -use location and use values
- [x]  Attribute information will be presented first, then followed by action based tools 
- [x]  need ability to zoom to existing and new features

FYI @jmhauck @jessnoo

**Comment by jessnoo** [comment]
Workflows as i understand them on duplicates:

- Feature is a duplicate and the user wants use the existing feature without changes

- Feature is a duplicate and the user wants to make changes to the existing feature (update existing feature's location or attribution)

- Feature is NOT a duplicate > moves into normal review but the feature needs to be geocoded first to ensure a valid location can be found.  If valid location - treated as normal feature feature review.  if no valid location - treated as location not found workflow

**Comment by NikkiGolding** [comment]
@jessnoo please use the information you submitted above to edit the original issue so we have clarity in the thread.

**Comment by jessnoo** [comment]
@NikkiGolding done. also reorged the content a little

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo while reviewing again to update this issue I noticed a couple of things that are not complete. I need to work on this issue a little more before it should be fully verified. 

Specifically, when the user is in the workflow for "is duplicate make changes" the UI should not show "Existing" and "File" headers twice. When you are reviewing items that are not duplicate the "Item:" label should not be shown. When the item has been flagged as "in not duplicate" we should navigate to the next item in the duplicate list if one exists or navigate to the main review pages that allows the user to step into one of the matched, unmatched, duplicate lists, or submit to the destination layer.

**Comment by jessnoo** [comment]
after fixing a duplicate with "is duplicate make changes", the item isn't moved to a 'matched' list so that it can be submitted.

**CSV:** [MarylandHospitals_993.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1601773/MarylandHospitals_993.zip)

**Repro Steps:**

1. submitted the attached csv to a target service, then loaded it into the widget again so that all items would be duplicated
2. open one of the duplicate items from the list
3. change action to "is duplicate make changes"
4. click to edit
5. make changes (seems like it doesn't matter what kind of change is made)
6. save changes
7. go back to main list screen >> notice that there is not a "matched" list and changes can't be submitted

![duplicate_list_mgmt](https://user-images.githubusercontent.com/6181441/34540751-86c84638-f08a-11e7-93aa-fbb2c1b5be31.gif)

**Comment by jmhauck** [comment]
So we can discuss this more but since the feature was flagged as "is duplicate make changes" on save the feature is flagged for an update call rather than adding a new feature to the service. The submit button is a problem, it should enable when one or more changes are made to the duplicate features like this rather than just when 1 or more features exist in the matched layer.

**Comment by NikkiGolding** [comment]
@jmhauck @jessnoo  I am not clear on where we are with the objectives laid out with the workflows and UI feedback.  I have modified the original requirement list to support a checklist. Please identify which of these items are complete. 

If there are subsequent issues that have popped up, they shoudl be split out into separate issues.

**Comment by jessnoo** [comment]
@NikkiGolding please let me know if there is an action you would like me to take here. it seems there's just one item left to be confirmed as implemented.

**Comment by NikkiGolding** [comment]
@jmhauck @jessnoo  I created a new issue to track the specific behavior list above from JEss regarding "is duplicate make changes" option.

**Comment by jmhauck** [comment]
@NikkiGolding I believe the workflows outlined are now done for this issue

**Comment by NikkiGolding** [comment]
Unable to verify with the current commit. Logging an issue. FYI @jmhauck

**Comment by NikkiGolding** [comment]
Verified baseline workflow identified is functioning.
