### ISSUE TITLE
Change color of edit button on review panels is confusing

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#986]
the blue button is confusing, especially after the edit button has been clicked and it's still active. 

first open the panel -- it's blue and clickable
![image](https://user-images.githubusercontent.com/6181441/32967277-dfb6dd18-cb91-11e7-888a-e5db69a6de5e.png)

after clicking it to go into edit mode -- now it's black and clickable, because clicking it cancels edits?
![image](https://user-images.githubusercontent.com/6181441/32967283-e862af78-cb91-11e7-919d-05ea294c4820.png)

**Recommendation**

first open panel: 
- Edit button: black
- save button: grayed out
- cancel button (new): grayed out

After clicking edit button: 
- Edit button: grayed out
- save button: grayed out
- cancel button (new): black

After making changes: 
- Edit button: grayed out
- save button: black
- cancel button (new): black

After clicking save or clicking cancel > starting state:  
- Edit button: black
- save button: grayed out
- cancel button (new): grayed out

@NikkiGolding fyi

**Comment by jessnoo** [comment]
minimum for first release -- just leave the edit black all the time. changing the colors is what confused me to begin i think . but for full release, there should be a cancel button.

**Comment by jmhauck** [comment]
Per conversation for beta will implement the full css change

**Comment by jmhauck** [comment]
Spoke with @jessnoo a bit more on this. The main idea is that we need to have something that will clearly indicate if editing mode is enabled or disabled. When this pencil icon is used in other parts of WAB it typically opens another dialog for some configuration rather than control or indicate state like it currently does here in DA. The approach discussed is to switch to a toggle button that is used in widgets like Filter:

Off:

![image](https://user-images.githubusercontent.com/2170893/34679520-79fe16ea-f453-11e7-8c05-0911a5fcae15.png)


On:
 
![image](https://user-images.githubusercontent.com/2170893/34679535-83d13184-f453-11e7-8f74-5e08441199d2.png)

We will still have a new cancel button that will allow temp modifications to be undone rather than when you disable edit mode.

@NikkiGolding

**Comment by NikkiGolding** [comment]
@jmhauck I prefer the pencil. This implementation is fine for beta. But, the mode style button is unintuitive. Leaving open but assigned to me. I will move to the next milestone to address the change to the pencil.

**Comment by aparveen** [comment]
We implemented a new icon, additional discussion needed for this issue in devtopia.
