### ISSUE TITLE
If i click back before submitting, i get in a weird state where i can't do anything

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#988]
@jmhauck @NikkiGolding fyi

[**Test App**](http://sg-em-devext.mapsdevext.arcgis.com/apps/webappviewer/index.html?id=046a59f0a1e04f7d920a04fd9bc2734a)
**Test File:** [MarylandHospitals.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1483761/MarylandHospitals.zip)

Let me know if you need me to reset the service

**Repro Steps**

1. With the test app, upload the test file
2. Set Location and Field information
3. Click Add to Map > Review lists are presented
4. Click Back -- whoops! -- can't get back to the review lists

**Expected behavior** -- clicking Next would return me to the review lists

![cf_whoopsbackbutton](https://user-images.githubusercontent.com/6181441/32968117-ec87025e-cb94-11e7-946d-965437ec3505.gif)

**Comment by jmhauck** [comment]
Should have a discussion around what happens when they are at the point that geocoding has occured and features have been added to the map and what all they can change vs starting the workflow over at that point. This is in addition to the issue that allows them to be in a place where the next button does not allow them to get back to the main review list.

**Comment by jmhauck** [comment]
Not fully complete until #980 is resolved

**Comment by jmhauck** [comment]
The commit above should have referenced 995 rather than this one.

**Comment by NikkiGolding** [comment]
@jmhauck  The label -in progress- is still on this issue, but it is assigned to me. Is this ready?

**Comment by NikkiGolding** [comment]
Verified.
